tableName: cityzip
primaryKey: zip+id
attributes:
- sourceName: /zip
  fieldName: zip
  mappingStrategy: StringLexBSI
  configuration:
    length: "0"
  type: String
- sourceName: /id
  fieldName: id
  mappingStrategy: StringLexBSI
  configuration:
    length: "0"
  type: String
- sourceName: /name
  fieldName: city
  mappingStrategy: StringLexBSI
  configuration:
    length: "0"
  type: String
- sourceName: /state
  fieldName: state
  mappingStrategy: StringEnum
  type: String
- sourceName: /id
  fieldName: city_id
  mappingStrategy: ParentRelation
  foreignKey: cities
  type: String
