tableName: deliveries_qa
primaryKey: delivery_id
attributes:
- fieldName: delivery_id
  mappingStrategy: StringLexBSI
  configuration:
    length: "0"
  type: String
- fieldName: line_id
  mappingStrategy: ParentRelation
  type: String
  foreignKey: lineitems_qa
- fieldName: status
  mappingStrategy: StringEnum
  type: String
